name = "iot-monitor"
main = "worker/index.js"
compatibility_date = "2025-06-27"

[[d1_databases]]
binding = "DB"
database_name = "monitorv2"
database_id = "d526cbb9-16d2-48cc-be73-559a7bddab2c"
remote = true

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false

[assets]
directory = "./public"
binding = "ASSETS"

[triggers]
crons = [
  "* * * * *",
  "*/10 * * * *",
  "0 8 * * *"       # 每天凌晨 0 點執行一次
]